//! marked 17.0.6's rules as its `Lexer` builds them with the default options: GitHub
//! flavored, without `breaks`. Generated by `tools/marked_rules.ts`.

use std::sync::LazyLock;

use tarnish_js::regexp::RegExp;

/// `block.gfm`.
#[allow(dead_code)]
pub struct Block {
    pub blockquote: RegExp,
    pub code: RegExp,
    pub def: RegExp,
    pub fences: RegExp,
    pub heading: RegExp,
    pub hr: RegExp,
    pub html: RegExp,
    pub lheading: RegExp,
    pub list: RegExp,
    pub newline: RegExp,
    pub paragraph: RegExp,
    pub table: RegExp,
    pub text: RegExp,
}

pub static BLOCK: LazyLock<Block> = LazyLock::new(|| Block {
    blockquote: RegExp::new(
        r"^( {0,3}> ?(([^\n]+(?:\n(?! {0,3}((?:-[\t ]*){3,}|(?:_[ \t]*){3,}|(?:\*[ \t]*){3,})(?:\n+|$)| {0,3}#{1,6}(?:\s|$)| {0,3}>| {0,3}(?:`{3,}(?=[^`\n]*\n)|~{3,})[^\n]*\n| {0,3}(?:[*+-]|1[.)])[ \t]|<\/?(?:address|article|aside|base|basefont|blockquote|body|caption|center|col|colgroup|dd|details|dialog|dir|div|dl|dt|fieldset|figcaption|figure|footer|form|frame|frameset|h[1-6]|head|header|hr|html|iframe|legend|li|link|main|menu|menuitem|meta|nav|noframes|ol|optgroup|option|p|param|search|section|summary|table|tbody|td|tfoot|th|thead|title|tr|track|ul)(?: +|\n|\/?>)|<(?:script|pre|style|textarea|!--)| +\n)[^\n]+)*)|[^\n]*)(?:\n|$))+",
        "",
    ),
    code: RegExp::new(r"^((?: {4}| {0,3}\t)[^\n]+(?:\n(?:[ \t]*(?:\n|$))*)?)+", ""),
    def: RegExp::new(
        r#"^ {0,3}\[((?!\s*\])(?:\\[\s\S]|[^\[\]\\])+)\]: *(?:\n[ \t]*)?([^<\s][^\s]*|<.*?>)(?:(?: +(?:\n[ \t]*)?| *\n[ \t]*)((?:"(?:\\"?|[^"\\])*"|'[^'\n]*(?:\n[^'\n]+)*\n?'|\([^()]*\))))? *(?:\n+|$)"#,
        "",
    ),
    fences: RegExp::new(
        r"^ {0,3}(`{3,}(?=[^`\n]*(?:\n|$))|~{3,})([^\n]*)(?:\n|$)(?:|([\s\S]*?)(?:\n|$))(?: {0,3}\1[~`]* *(?=\n|$)|$)",
        "",
    ),
    heading: RegExp::new(r"^ {0,3}(#{1,6})(?=\s|$)(.*)(?:\n+|$)", ""),
    hr: RegExp::new(
        r"^ {0,3}((?:-[\t ]*){3,}|(?:_[ \t]*){3,}|(?:\*[ \t]*){3,})(?:\n+|$)",
        "",
    ),
    html: RegExp::new(
        r#"^ {0,3}(?:<(script|pre|style|textarea)[\s>][\s\S]*?(?:<\/\1>[^\n]*\n+|$)|<!--(?:-?>|[\s\S]*?(?:-->|$))[^\n]*(\n+|$)|<\?[\s\S]*?(?:\?>\n*|$)|<![A-Z][\s\S]*?(?:>\n*|$)|<!\[CDATA\[[\s\S]*?(?:\]\]>\n*|$)|<\/?(address|article|aside|base|basefont|blockquote|body|caption|center|col|colgroup|dd|details|dialog|dir|div|dl|dt|fieldset|figcaption|figure|footer|form|frame|frameset|h[1-6]|head|header|hr|html|iframe|legend|li|link|main|menu|menuitem|meta|nav|noframes|ol|optgroup|option|p|param|search|section|summary|table|tbody|td|tfoot|th|thead|title|tr|track|ul)(?: +|\n|\/?>)[\s\S]*?(?:(?:\n[ 	]*)+\n|$)|<(?!script|pre|style|textarea)([a-z][\w-]*)(?: +[a-zA-Z:_][\w.:-]*(?: *= *"[^"\n]*"| *= *'[^'\n]*'| *= *[^\s"'=<>`]+)?)*? *\/?>(?=[ \t]*(?:\n|$))[\s\S]*?(?:(?:\n[ 	]*)+\n|$)|<\/(?!script|pre|style|textarea)[a-z][\w-]*\s*>(?=[ \t]*(?:\n|$))[\s\S]*?(?:(?:\n[ 	]*)+\n|$))"#,
        "i",
    ),
    lheading: RegExp::new(
        r"^(?! {0,3}(?:[*+-]|\d{1,9}[.)]) |(?: {4}| {0,3}\t)| {0,3}(?:`{3,}|~{3,})| {0,3}>| {0,3}#{1,6}| {0,3}<[^\n>]+>\n| {0,3}\|?(?:[:\- ]*\|)+[\:\- ]*\n)((?:.|\n(?!\s*?\n| {0,3}(?:[*+-]|\d{1,9}[.)]) |(?: {4}| {0,3}\t)| {0,3}(?:`{3,}|~{3,})| {0,3}>| {0,3}#{1,6}| {0,3}<[^\n>]+>\n| {0,3}\|?(?:[:\- ]*\|)+[\:\- ]*\n))+?)\n {0,3}(=+|-+) *(?:\n+|$)",
        "",
    ),
    list: RegExp::new(r"^( {0,3}(?:[*+-]|\d{1,9}[.)]))([ \t][^\n]+?)?(?:\n|$)", ""),
    newline: RegExp::new(r"^(?:[ \t]*(?:\n|$))+", ""),
    paragraph: RegExp::new(
        r"^([^\n]+(?:\n(?! {0,3}((?:-[\t ]*){3,}|(?:_[ \t]*){3,}|(?:\*[ \t]*){3,})(?:\n+|$)| {0,3}#{1,6}(?:\s|$)| {0,3}>| {0,3}(?:`{3,}(?=[^`\n]*\n)|~{3,})[^\n]*\n| {0,3}(?:[*+-]|1[.)])[ \t]|<\/?(?:address|article|aside|base|basefont|blockquote|body|caption|center|col|colgroup|dd|details|dialog|dir|div|dl|dt|fieldset|figcaption|figure|footer|form|frame|frameset|h[1-6]|head|header|hr|html|iframe|legend|li|link|main|menu|menuitem|meta|nav|noframes|ol|optgroup|option|p|param|search|section|summary|table|tbody|td|tfoot|th|thead|title|tr|track|ul)(?: +|\n|\/?>)|<(?:script|pre|style|textarea|!--)| *([^\n ].*)\n {0,3}((?:\| *)?:?-+:? *(?:\| *:?-+:? *)*(?:\| *)?)(?:\n((?:(?! *\n| {0,3}((?:-[\t ]*){3,}|(?:_[ \t]*){3,}|(?:\*[ \t]*){3,})(?:\n+|$)| {0,3}#{1,6}(?:\s|$)| {0,3}>|(?: {4}| {0,3}	)[^\n]| {0,3}(?:`{3,}(?=[^`\n]*\n)|~{3,})[^\n]*\n| {0,3}(?:[*+-]|1[.)])[ \t]|<\/?(?:address|article|aside|base|basefont|blockquote|body|caption|center|col|colgroup|dd|details|dialog|dir|div|dl|dt|fieldset|figcaption|figure|footer|form|frame|frameset|h[1-6]|head|header|hr|html|iframe|legend|li|link|main|menu|menuitem|meta|nav|noframes|ol|optgroup|option|p|param|search|section|summary|table|tbody|td|tfoot|th|thead|title|tr|track|ul)(?: +|\n|\/?>)|<(?:script|pre|style|textarea|!--)).*(?:\n|$))*)\n*|$)| +\n)[^\n]+)*)",
        "",
    ),
    table: RegExp::new(
        r"^ *([^\n ].*)\n {0,3}((?:\| *)?:?-+:? *(?:\| *:?-+:? *)*(?:\| *)?)(?:\n((?:(?! *\n| {0,3}((?:-[\t ]*){3,}|(?:_[ \t]*){3,}|(?:\*[ \t]*){3,})(?:\n+|$)| {0,3}#{1,6}(?:\s|$)| {0,3}>|(?: {4}| {0,3}	)[^\n]| {0,3}(?:`{3,}(?=[^`\n]*\n)|~{3,})[^\n]*\n| {0,3}(?:[*+-]|1[.)])[ \t]|<\/?(?:address|article|aside|base|basefont|blockquote|body|caption|center|col|colgroup|dd|details|dialog|dir|div|dl|dt|fieldset|figcaption|figure|footer|form|frame|frameset|h[1-6]|head|header|hr|html|iframe|legend|li|link|main|menu|menuitem|meta|nav|noframes|ol|optgroup|option|p|param|search|section|summary|table|tbody|td|tfoot|th|thead|title|tr|track|ul)(?: +|\n|\/?>)|<(?:script|pre|style|textarea|!--)).*(?:\n|$))*)\n*|$)",
        "",
    ),
    text: RegExp::new(r"^[^\n]+", ""),
});

/// `inline.gfm`.
#[allow(dead_code)]
pub struct Inline {
    pub backpedal: RegExp,
    pub any_punctuation: RegExp,
    pub autolink: RegExp,
    pub block_skip: RegExp,
    pub br: RegExp,
    pub code: RegExp,
    pub del: RegExp,
    pub del_l_delim: RegExp,
    pub del_r_delim: RegExp,
    pub em_strong_l_delim: RegExp,
    pub em_strong_r_delim_ast: RegExp,
    pub em_strong_r_delim_und: RegExp,
    pub escape: RegExp,
    pub link: RegExp,
    pub nolink: RegExp,
    pub punctuation: RegExp,
    pub reflink: RegExp,
    pub reflink_search: RegExp,
    pub tag: RegExp,
    pub text: RegExp,
    pub url: RegExp,
}

pub static INLINE: LazyLock<Inline> = LazyLock::new(|| Inline {
    backpedal: RegExp::new(
        r#"(?:[^?!.,:;*_'"~()&]+|\([^)]*\)|&(?![a-zA-Z0-9]+;$)|[?!.,:;*_'"~)]+(?!$))+"#,
        "",
    ),
    any_punctuation: RegExp::new(r"\\([\p{P}\p{S}])", "gu"),
    autolink: RegExp::new(
        r"^<([a-zA-Z][a-zA-Z0-9+.-]{1,31}:[^\s\x00-\x1f<>]*|[a-zA-Z0-9.!#$%&'*+/=?_`{|}~-]+(@)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+(?![-_]))>",
        "",
    ),
    block_skip: RegExp::new(
        r"\[(?:[^\[\]`]|(?<a>`+)[^`]+\k<a>(?!`))*?\]\((?:\\[\s\S]|[^\\\(\)]|\((?:\\[\s\S]|[^\\\(\)])*\))*\)|(?<!`)()(?<b>`+)[^`]+\k<b>(?!`)|<(?! )[^<>]*?>",
        "g",
    ),
    br: RegExp::new(r"^( {2,}|\\)\n(?!\s*$)", ""),
    code: RegExp::new(r"^(`+)([^`]|[^`][\s\S]*?[^`])\1(?!`)", ""),
    del: RegExp::new(
        r"^(~~?)(?=[^\s~])((?:\\[\s\S]|[^\\])*?(?:\\[\s\S]|[^\s~\\]))\1(?=[^~]|$)",
        "",
    ),
    del_l_delim: RegExp::new(r"^~~?(?:((?!~)[\p{P}\p{S}])|[^\s~])", "u"),
    del_r_delim: RegExp::new(
        r"^[^~]+(?=[^~])|(?!~)[\p{P}\p{S}](~~?)(?=[\s]|$)|[^\s\p{P}\p{S}](~~?)(?!~)(?=[\s\p{P}\p{S}]|$)|(?!~)[\s\p{P}\p{S}](~~?)(?=[^\s\p{P}\p{S}])|[\s](~~?)(?!~)(?=[\p{P}\p{S}])|(?!~)[\p{P}\p{S}](~~?)(?!~)(?=[\p{P}\p{S}])|[^\s\p{P}\p{S}](~~?)(?=[^\s\p{P}\p{S}])",
        "gu",
    ),
    em_strong_l_delim: RegExp::new(
        r"^(?:\*+(?:((?!\*)(?!~)[\p{P}\p{S}])|([^\s*]))?)|^_+(?:((?!_)(?!~)[\p{P}\p{S}])|([^\s_]))?",
        "u",
    ),
    em_strong_r_delim_ast: RegExp::new(
        r"^[^_*]*?__[^_*]*?\*[^_*]*?(?=__)|[^*]+(?=[^*])|(?!\*)(?!~)[\p{P}\p{S}](\*+)(?=[\s]|$)|(?:[^\s\p{P}\p{S}]|~)(\*+)(?!\*)(?=(?!~)[\s\p{P}\p{S}]|$)|(?!\*)(?!~)[\s\p{P}\p{S}](\*+)(?=(?:[^\s\p{P}\p{S}]|~))|[\s](\*+)(?!\*)(?=(?!~)[\p{P}\p{S}])|(?!\*)(?!~)[\p{P}\p{S}](\*+)(?!\*)(?=(?!~)[\p{P}\p{S}])|(?:[^\s\p{P}\p{S}]|~)(\*+)(?=(?:[^\s\p{P}\p{S}]|~))",
        "gu",
    ),
    em_strong_r_delim_und: RegExp::new(
        r"^[^_*]*?\*\*[^_*]*?_[^_*]*?(?=\*\*)|[^_]+(?=[^_])|(?!_)[\p{P}\p{S}](_+)(?=[\s]|$)|[^\s\p{P}\p{S}](_+)(?!_)(?=[\s\p{P}\p{S}]|$)|(?!_)[\s\p{P}\p{S}](_+)(?=[^\s\p{P}\p{S}])|[\s](_+)(?!_)(?=[\p{P}\p{S}])|(?!_)[\p{P}\p{S}](_+)(?!_)(?=[\p{P}\p{S}])",
        "gu",
    ),
    escape: RegExp::new(r##"^\\([!"#$%&'()*+,\-./:;<=>?@\[\]\\^_`{|}~])"##, ""),
    link: RegExp::new(
        r#"^!?\[((?:\[(?:\\[\s\S]|[^\[\]\\])*\]|\\[\s\S]|`+(?!`)[^`]*?`+(?!`)|``+(?=\])|[^\[\]\\`])*?)\]\(\s*(<(?:\\.|[^\n<>\\])+>|[^ \t\n\x00-\x1f]*)(?:(?:[ \t]+(?:\n[ \t]*)?|\n[ \t]*)("(?:\\"?|[^"\\])*"|'(?:\\'?|[^'\\])*'|\((?:\\\)?|[^)\\])*\)))?\s*\)"#,
        "",
    ),
    nolink: RegExp::new(r"^!?\[((?!\s*\])(?:\\[\s\S]|[^\[\]\\])+)\](?:\[\])?", ""),
    punctuation: RegExp::new(r"^((?![*_])[\s\p{P}\p{S}])", "u"),
    reflink: RegExp::new(
        r"^!?\[((?:\[(?:\\[\s\S]|[^\[\]\\])*\]|\\[\s\S]|`+(?!`)[^`]*?`+(?!`)|``+(?=\])|[^\[\]\\`])*?)\]\[((?!\s*\])(?:\\[\s\S]|[^\[\]\\])+)\]",
        "",
    ),
    reflink_search: RegExp::new(
        r"!?\[((?:\[(?:\\[\s\S]|[^\[\]\\])*\]|\\[\s\S]|`+(?!`)[^`]*?`+(?!`)|``+(?=\])|[^\[\]\\`])*?)\]\[((?!\s*\])(?:\\[\s\S]|[^\[\]\\])+)\]|!?\[((?!\s*\])(?:\\[\s\S]|[^\[\]\\])+)\](?:\[\])?(?!\()",
        "g",
    ),
    tag: RegExp::new(
        r#"^<!--(?:-?>|[\s\S]*?-->)|^<\/[a-zA-Z][\w:-]*\s*>|^<[a-zA-Z][\w-]*(?:\s+[a-zA-Z:_][\w.:-]*(?:\s*=\s*"[^"]*"|\s*=\s*'[^']*'|\s*=\s*[^\s"'=<>`]+)?)*?\s*\/?>|^<\?[\s\S]*?\?>|^<![a-zA-Z]+\s[\s\S]*?>|^<!\[CDATA\[[\s\S]*?\]\]>"#,
        "",
    ),
    text: RegExp::new(
        r"^([`~]+|[^`~])(?:(?= {2,}\n)|(?=[a-zA-Z0-9.!#$%&'*+\/=?_`{\|}~-]+@)|[\s\S]*?(?:(?=[\\<!\[`*~_]|\b_|[hH][tT][tT][pP][sS]?|[fF][tT][pP]:\/\/|www\.|$)|[^ ](?= {2,}\n)|[^a-zA-Z0-9.!#$%&'*+\/=?_`{\|}~-](?=[a-zA-Z0-9.!#$%&'*+\/=?_`{\|}~-]+@)))",
        "",
    ),
    url: RegExp::new(
        r"^((?:[hH][tT][tT][pP][sS]?|[fF][tT][pP]):\/\/|www\.)(?:[a-zA-Z0-9\-]+\.?)+[^\s<]*|^[A-Za-z0-9._+-]+(@)[a-zA-Z0-9-_]+(?:\.[a-zA-Z0-9-_]*[a-zA-Z0-9])+(?![-_])",
        "",
    ),
});

/// `other`.
#[allow(dead_code)]
pub struct Other {
    pub code_remove_indent: RegExp,
    pub output_link_replace: RegExp,
    pub indent_code_compensation: RegExp,
    pub beginning_space: RegExp,
    pub ending_hash: RegExp,
    pub starting_space_char: RegExp,
    pub ending_space_char: RegExp,
    pub non_space_char: RegExp,
    pub new_line_char_global: RegExp,
    pub tab_char_global: RegExp,
    pub multiple_space_global: RegExp,
    pub blank_line: RegExp,
    pub double_blank_line: RegExp,
    pub blockquote_start: RegExp,
    pub blockquote_setext_replace: RegExp,
    pub blockquote_setext_replace2: RegExp,
    pub list_replace_nesting: RegExp,
    pub list_is_task: RegExp,
    pub list_replace_task: RegExp,
    pub list_task_checkbox: RegExp,
    pub any_line: RegExp,
    pub href_brackets: RegExp,
    pub table_delimiter: RegExp,
    pub table_align_chars: RegExp,
    pub table_row_blank_line: RegExp,
    pub table_align_right: RegExp,
    pub table_align_center: RegExp,
    pub table_align_left: RegExp,
    pub start_a_tag: RegExp,
    pub end_a_tag: RegExp,
    pub start_pre_script_tag: RegExp,
    pub end_pre_script_tag: RegExp,
    pub start_angle_bracket: RegExp,
    pub end_angle_bracket: RegExp,
    pub pedantic_href_title: RegExp,
    pub unicode_alpha_numeric: RegExp,
    pub escape_test: RegExp,
    pub escape_replace: RegExp,
    pub escape_test_no_encode: RegExp,
    pub escape_replace_no_encode: RegExp,
    pub caret: RegExp,
    pub percent_decode: RegExp,
    pub find_pipe: RegExp,
    pub split_pipe: RegExp,
    pub slash_pipe: RegExp,
    pub carriage_return: RegExp,
    pub space_line: RegExp,
    pub not_space_start: RegExp,
    pub ending_newline: RegExp,
}

pub static OTHER: LazyLock<Other> = LazyLock::new(|| Other {
    code_remove_indent: RegExp::new(r"^(?: {1,4}| {0,3}\t)", "gm"),
    output_link_replace: RegExp::new(r"\\([\[\]])", "g"),
    indent_code_compensation: RegExp::new(r"^(\s+)(?:```)", ""),
    beginning_space: RegExp::new(r"^\s+", ""),
    ending_hash: RegExp::new(r"#$", ""),
    starting_space_char: RegExp::new(r"^ ", ""),
    ending_space_char: RegExp::new(r" $", ""),
    non_space_char: RegExp::new(r"[^ ]", ""),
    new_line_char_global: RegExp::new(r"\n", "g"),
    tab_char_global: RegExp::new(r"\t", "g"),
    multiple_space_global: RegExp::new(r"\s+", "g"),
    blank_line: RegExp::new(r"^[ \t]*$", ""),
    double_blank_line: RegExp::new(r"\n[ \t]*\n[ \t]*$", ""),
    blockquote_start: RegExp::new(r"^ {0,3}>", ""),
    blockquote_setext_replace: RegExp::new(r"\n {0,3}((?:=+|-+) *)(?=\n|$)", "g"),
    blockquote_setext_replace2: RegExp::new(r"^ {0,3}>[ \t]?", "gm"),
    list_replace_nesting: RegExp::new(r"^ {1,4}(?=( {4})*[^ ])", "g"),
    list_is_task: RegExp::new(r"^\[[ xX]\] +\S", ""),
    list_replace_task: RegExp::new(r"^\[[ xX]\] +", ""),
    list_task_checkbox: RegExp::new(r"\[[ xX]\]", ""),
    any_line: RegExp::new(r"\n.*\n", ""),
    href_brackets: RegExp::new(r"^<(.*)>$", ""),
    table_delimiter: RegExp::new(r"[:|]", ""),
    table_align_chars: RegExp::new(r"^\||\| *$", "g"),
    table_row_blank_line: RegExp::new(r"\n[ \t]*$", ""),
    table_align_right: RegExp::new(r"^ *-+: *$", ""),
    table_align_center: RegExp::new(r"^ *:-+: *$", ""),
    table_align_left: RegExp::new(r"^ *:-+ *$", ""),
    start_a_tag: RegExp::new(r"^<a ", "i"),
    end_a_tag: RegExp::new(r"^<\/a>", "i"),
    start_pre_script_tag: RegExp::new(r"^<(pre|code|kbd|script)(\s|>)", "i"),
    end_pre_script_tag: RegExp::new(r"^<\/(pre|code|kbd|script)(\s|>)", "i"),
    start_angle_bracket: RegExp::new(r"^<", ""),
    end_angle_bracket: RegExp::new(r">$", ""),
    pedantic_href_title: RegExp::new(r#"^([^'"]*[^\s])\s+(['"])(.*)\2"#, ""),
    unicode_alpha_numeric: RegExp::new(r"[\p{L}\p{N}]", "u"),
    escape_test: RegExp::new(r#"[&<>"']"#, ""),
    escape_replace: RegExp::new(r#"[&<>"']"#, "g"),
    escape_test_no_encode: RegExp::new(r#"[<>"']|&(?!(#\d{1,7}|#[Xx][a-fA-F0-9]{1,6}|\w+);)"#, ""),
    escape_replace_no_encode: RegExp::new(
        r#"[<>"']|&(?!(#\d{1,7}|#[Xx][a-fA-F0-9]{1,6}|\w+);)"#,
        "g",
    ),
    caret: RegExp::new(r"(^|[^\[])\^", "g"),
    percent_decode: RegExp::new(r"%25", "g"),
    find_pipe: RegExp::new(r"\|", "g"),
    split_pipe: RegExp::new(r" \|", ""),
    slash_pipe: RegExp::new(r"\\\|", "g"),
    carriage_return: RegExp::new(r"\r\n|\r", "g"),
    space_line: RegExp::new(r"^ +$", "gm"),
    not_space_start: RegExp::new(r"^\S*", ""),
    ending_newline: RegExp::new(r"\n$", ""),
});
