// Builds tarnish-css-wasm and writes it into a checkout of the linkedom fork:
//
//   node harness/css-wasm.mjs ../linkedom
//
// Needs the wasm32-unknown-unknown target and wasm-bindgen-cli of the version the crate pins.
// npx fetches binaryen's wasm-opt, of the version below.

import { execFileSync } from "node:child_process"
import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { dirname, join, relative } from "node:path"
import { pathToFileURL } from "node:url"

const BINARYEN = "132.0.0"
const TARGET = "wasm32-unknown-unknown"
// What rustc's default wasm CPU enables: wasm-bindgen drops the section that would tell wasm-opt.
const FEATURES = [
  "bulk-memory",
  "bulk-memory-opt",
  "call-indirect-overlong",
  "multivalue",
  "mutable-globals",
  "nontrapping-float-to-int",
  "reference-types",
  "sign-ext",
]

const root = new URL("..", import.meta.url).pathname
const fork = process.argv[2]
if (!fork) throw new Error("usage: node harness/css-wasm.mjs <linkedom checkout>")
const into = join(fork, "esm/shared/css")

const run = (command, args) => execFileSync(command, args, { cwd: root, encoding: "utf8", maxBuffer: 1 << 28 })

const pinned = readFileSync(join(root, "crates/tarnish-css-wasm/Cargo.toml"), "utf8").match(
  /wasm-bindgen = "=([^"]+)"/,
)[1]
const installed = run("wasm-bindgen", ["--version"]).trim()
if (installed !== `wasm-bindgen ${pinned}`)
  throw new Error(`the crate pins wasm-bindgen ${pinned}, but ${installed} is installed`)

const sources = ["crates/tarnish-css", "crates/tarnish-css-wasm", "Cargo.lock", "Cargo.toml", "harness/css-wasm.mjs"]
const commit = run("git", ["log", "-1", "--format=%H", "--", ...sources]).trim()
const dirty = run("git", ["status", "--porcelain", "--", ...sources]).trim() ? "-dirty" : ""
const built = `tarnish ${commit.slice(0, 7)}${dirty}`

run("cargo", ["build", "-p", "tarnish-css-wasm", "--target", TARGET, "--profile", "wasm", "--locked"])
const out = mkdtempSync(join(tmpdir(), "tarnish-css-"))
try {
  run("wasm-bindgen", [
    "--target",
    "web",
    "--omit-default-module-path",
    "--no-typescript",
    "--out-dir",
    out,
    join(root, `target/${TARGET}/wasm/tarnish_css_wasm.wasm`),
  ])
  const wasm = join(out, "engine.wasm")
  run("npx", [
    "--yes",
    "--package",
    `binaryen@${BINARYEN}`,
    "--",
    "wasm-opt",
    "-Oz",
    ...FEATURES.map(feature => `--enable-${feature}`),
    join(out, "tarnish_css_wasm_bg.wasm"),
    "-o",
    wasm,
  ])

  // The glue's default export fetches the module; the fork instantiates it from the bytes with
  // initSync, and ascjs would make a default export the whole CommonJS module.
  const ending = "export { initSync, __wbg_init as default };\n"
  const glue = readFileSync(join(out, "tarnish_css_wasm.js"), "utf8")
  if (!glue.endsWith(ending)) throw new Error(`the glue no longer ends with ${JSON.stringify(ending)}`)
  const engine = await import(pathToFileURL(join(out, "tarnish_css_wasm.js")))
  engine.initSync({ module: readFileSync(wasm) })

  const header =
    `// Generated by tarnish's harness/css-wasm.mjs from ${built}: do not edit.\n` +
    `// element.style is tarnish-css, on stylo, Servo's CSS engine, as WebAssembly: engine() is ${engine.engine()}.\n` +
    "// The crates it's built from, with their licences and sources: esm/shared/css/THIRD-PARTY.md.\n"
  writeFileSync(join(into, "engine.js"), header + glue.slice(0, -ending.length) + "export { initSync };\n")
  writeFileSync(join(into, "engine.wasm"), readFileSync(wasm))
  writeFileSync(join(into, "THIRD-PARTY.md"), notices())
} finally {
  rmSync(out, { recursive: true, force: true })
}

// The crates compiled into the module: tarnish-css-wasm's dependencies on the target, but not
// what only build scripts and procedural macros run on.
function crates() {
  const metadata = JSON.parse(run("cargo", ["metadata", "--format-version", "1", "--locked", "--filter-platform", TARGET]))
  const packages = new Map(metadata.packages.map(pkg => [pkg.id, pkg]))
  const nodes = new Map(metadata.resolve.nodes.map(node => [node.id, node]))
  const found = new Map()
  const visit = id => {
    if (found.has(id)) return
    const pkg = packages.get(id)
    found.set(id, pkg)
    if (pkg.targets.some(target => target.kind.includes("proc-macro"))) return
    for (const dep of nodes.get(id).deps) if (dep.dep_kinds.some(({ kind }) => kind === null)) visit(dep.pkg)
  }
  visit(metadata.packages.find(pkg => pkg.name === "tarnish-css-wasm").id)
  const order = ({ name, version }) => `${name} ${version}`
  const sorted = [...found.values()].sort((a, b) => (order(a) < order(b) ? -1 : 1))
  return { crates: sorted, workspace: metadata.workspace_root }
}

function notices() {
  const { crates: all, workspace } = crates()
  const source = pkg =>
    pkg.source === null
      ? `${pkg.repository}/tree/${commit}/${relative(workspace, dirname(pkg.manifest_path))}`
      : `https://crates.io/crates/${pkg.name}/${pkg.version}`
  const licences = dir =>
    readdirSync(dir)
      .filter(name => /^(licen[cs]e|copying|copyright|notice)/i.test(name))
      .sort()
      .map(name => readFileSync(join(dir, name), "utf8").trim())
  const texts = new Map()
  const without = []
  for (const pkg of all) {
    if (!pkg.license) throw new Error(`${pkg.name} gives no licence expression`)
    let own = licences(dirname(pkg.manifest_path))
    if (!own.length && pkg.source === null) own = licences(workspace)
    if (!own.length) without.push(pkg)
    for (const text of own) texts.set(text, [...(texts.get(text) ?? []), `${pkg.name} ${pkg.version}`])
  }
  const shipped = all.filter(pkg => !without.includes(pkg)).map(pkg => pkg.license)
  for (const pkg of without) {
    const ids = pkg.license.split(/[\s()]+/).filter(id => id && !["AND", "OR", "WITH"].includes(id))
    const missing = ids.filter(id => !shipped.some(licence => licence.includes(id)))
    if (missing.length) throw new Error(`${pkg.name} ships no licence text, and no other crate ships ${missing}'s`)
  }

  const fence = text => "`".repeat(Math.max(3, ...[...text.matchAll(/`+/g)].map(([ticks]) => ticks.length + 1)))
  return [
    "# Third-party notices",
    "",
    `Generated by tarnish's harness/css-wasm.mjs from ${built}: do not edit.`,
    "",
    "`engine.wasm`, and `worker.js`, which holds it too, are compiled from these Rust crates. Each",
    "one's source is at its link.",
    "",
    "| Crate | Version | Licence | Source |",
    "| --- | --- | --- | --- |",
    ...all.map(pkg => `| ${pkg.name} | ${pkg.version} | ${pkg.license.replaceAll("|", "\\|")} | ${source(pkg)} |`),
    "",
    "## Licence texts",
    "",
    "Each text the crates ship, once, headed by the crates that ship it. These crates ship none, and",
    "their licences' texts are among the others:",
    "",
    ...without.map(pkg => `- ${pkg.name} ${pkg.version}, ${pkg.license}, by ${pkg.authors.join(", ")}`),
    ...[...texts].flatMap(([text, names]) => ["", `### ${names.join(", ")}`, "", `${fence(text)}text`, text, fence(text)]),
    "",
  ].join("\n")
}
