// Prints src/marked/rules.rs: the rules marked's Lexer builds with the default options. From the
// repo root:
//
//   npx tsx crates/tarnish-markdown/tools/marked_rules.ts | rustfmt --edition 2024 \
//     > crates/tarnish-markdown/src/marked/rules.rs
import { createRequire } from "node:module"
import { Lexer } from "marked"

const { version } = createRequire(import.meta.url)("marked/package.json")

const { tokenizer } = new Lexer() as unknown as {
  tokenizer: { rules: Record<"block" | "inline" | "other", Record<string, unknown>> }
}

const snakeCase = (name: string) =>
  name
    .replace(/^_/, "")
    .replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`)
    .replace(/^_/, "")

const rustString = (source: string) => {
  const hashes = "#".repeat(
    Math.max(0, ...[...source.matchAll(/"(#*)/g)].map((match) => match[1].length + 1)),
  )
  return `r${hashes}"${source}"${hashes}`
}

const sections = [
  ["block", "Block", "`block.gfm`"],
  ["inline", "Inline", "`inline.gfm`"],
  ["other", "Other", "`other`"],
] as const

let out = `//! marked ${version}'s rules as its \`Lexer\` builds them with the default options: GitHub
//! flavored, without \`breaks\`. Generated by \`tools/marked_rules.ts\`.

use std::sync::LazyLock;

use tarnish_js::regexp::RegExp;
`

for (const [key, type, doc] of sections) {
  const rules = Object.entries(tokenizer.rules[key]).filter(
    (entry): entry is [string, RegExp] => entry[1] instanceof RegExp,
  )
  out += `
/// ${doc}.
#[allow(dead_code)]
pub struct ${type} {
${rules.map(([name]) => `    pub ${snakeCase(name)}: RegExp,`).join("\n")}
}

pub static ${key.toUpperCase()}: LazyLock<${type}> = LazyLock::new(|| ${type} {
${rules
  .map(
    ([name, rule]) =>
      `    ${snakeCase(name)}: RegExp::new(${rustString(rule.source)}, "${rule.flags}"),`,
  )
  .join("\n")}
});
`
}

process.stdout.write(out)
